# Generated by Django 2.2.6 on 2020-10-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201011_1155'),
    ]

    operations = [
    ]
