# Generated by Django 2.2.6 on 2020-11-12 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_message_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2014, 8, 1), verbose_name='date send message'),
            preserve_default=False,
        ),
    ]
